-- ============================================================
-- ZAPMRO — 8b. RLS: ENABLE + POLICIES (isolamento por usuario)
-- Gerado a partir do banco de origem (pg_policies).
-- Idempotente: pode rodar quantas vezes precisar.
-- ============================================================

BEGIN;

-- 1) Liga RLS em todas as tabelas que tinham RLS na origem
ALTER TABLE public.admin_announcement_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ads_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ads_balance_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ads_client_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ads_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ads_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.broadcast_email_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.call_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.corretor_announcement_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.corretor_announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.corretor_corrections_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.corretor_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.corretor_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.corretor_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.created_accesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_access_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_broadcasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_flow_executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_flow_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_flows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_google_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_google_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_sales_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_scheduled_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_webhook_delivery_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crm_webhooks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.desconto_alunos_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.free_trial_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.free_trial_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.infinitepay_webhook_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inteligencia_fotos_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inteligencia_fotos_generations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inteligencia_fotos_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inteligencia_fotos_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inteligencia_fotos_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.license_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.license_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.live_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.live_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.live_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metodo_seguidor_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metodo_seguidor_banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metodo_seguidor_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metodo_seguidor_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metodo_seguidor_upsells ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metodo_seguidor_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metodo_seguidor_videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mro_direct_ai_pauses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mro_direct_automations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mro_direct_known_followers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mro_direct_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mro_direct_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mro_euro_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mro_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mro_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mro_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mro_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mro_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mro_strategies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.paid_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promo33_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prompts_mro_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prompts_mro_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prompts_mro_payment_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prompts_mro_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prompts_mro_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promptsin_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promptsin_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promptsin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renda_extra_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renda_extra_aula_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renda_extra_aula_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renda_extra_aula_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renda_extra_email_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renda_extra_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renda_extra_materiais ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renda_extra_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renda_extra_v2_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renda_extra_v2_email_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renda_extra_v2_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renda_extra_v2_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rendaext_analytics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rendaext_audio_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rendaext_email_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rendaext_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rendaext_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rendaext_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales_tutorials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.squarecloud_user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_page_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_page_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wpp_bot_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wpp_bot_messages_v2 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wpp_bot_session ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wpp_bot_session_v2 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wpp_bot_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wpp_bot_settings_v2 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wpp_connection_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zapi_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zapi_flow_executions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zapi_flow_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zapi_flows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zapi_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zapi_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zapmro_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zapmro_users ENABLE ROW LEVEL SECURITY;

-- 2) Recria todas as policies
DROP POLICY IF EXISTS "Users manage own views" ON public.admin_announcement_views; CREATE POLICY "Users manage own views" ON public.admin_announcement_views AS PERMISSIVE FOR ALL TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Authed can read active announcements" ON public.admin_announcements; CREATE POLICY "Authed can read active announcements" ON public.admin_announcements AS PERMISSIVE FOR SELECT TO authenticated USING ((active = true));
DROP POLICY IF EXISTS "Service role only on ads_admins" ON public.ads_admins; CREATE POLICY "Service role only on ads_admins" ON public.ads_admins AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on ads_balance_orders" ON public.ads_balance_orders; CREATE POLICY "Service role only on ads_balance_orders" ON public.ads_balance_orders AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on ads_client_data" ON public.ads_client_data; CREATE POLICY "Service role only on ads_client_data" ON public.ads_client_data AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on ads_orders" ON public.ads_orders; CREATE POLICY "Service role only on ads_orders" ON public.ads_orders AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on ads_users" ON public.ads_users; CREATE POLICY "Service role only on ads_users" ON public.ads_users AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Anyone can insert broadcast logs" ON public.broadcast_email_logs; CREATE POLICY "Anyone can insert broadcast logs" ON public.broadcast_email_logs AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Service role full access on broadcast_email_logs" ON public.broadcast_email_logs; CREATE POLICY "Service role full access on broadcast_email_logs" ON public.broadcast_email_logs AS RESTRICTIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Anyone can delete analytics" ON public.call_analytics; CREATE POLICY "Anyone can delete analytics" ON public.call_analytics AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS "Anyone can insert analytics" ON public.call_analytics; CREATE POLICY "Anyone can insert analytics" ON public.call_analytics AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Anyone can read analytics" ON public.call_analytics; CREATE POLICY "Anyone can read analytics" ON public.call_analytics AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "Allow public insert on corretor_announcement_views" ON public.corretor_announcement_views; CREATE POLICY "Allow public insert on corretor_announcement_views" ON public.corretor_announcement_views AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Service role read on corretor_announcement_views" ON public.corretor_announcement_views; CREATE POLICY "Service role read on corretor_announcement_views" ON public.corretor_announcement_views AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Allow public read on corretor_announcements" ON public.corretor_announcements; CREATE POLICY "Allow public read on corretor_announcements" ON public.corretor_announcements AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "Allow public insert on corretor_corrections_log" ON public.corretor_corrections_log; CREATE POLICY "Allow public insert on corretor_corrections_log" ON public.corretor_corrections_log AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Service role only on corretor_orders" ON public.corretor_orders; CREATE POLICY "Service role only on corretor_orders" ON public.corretor_orders AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on created_accesses" ON public.created_accesses; CREATE POLICY "Service role full access on created_accesses" ON public.created_accesses AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Users can insert their own logs" ON public.crm_access_logs; CREATE POLICY "Users can insert their own logs" ON public.crm_access_logs AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can view their own logs" ON public.crm_access_logs; CREATE POLICY "Users can view their own logs" ON public.crm_access_logs AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_activities; CREATE POLICY "Users can only access their own data" ON public.crm_activities AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_activities; CREATE POLICY "Users can only delete their own data" ON public.crm_activities AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_activities; CREATE POLICY "Users can only insert their own data" ON public.crm_activities AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_activities; CREATE POLICY "Users can only update their own data" ON public.crm_activities AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_broadcasts; CREATE POLICY "Users can only access their own data" ON public.crm_broadcasts AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_broadcasts; CREATE POLICY "Users can only delete their own data" ON public.crm_broadcasts AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_broadcasts; CREATE POLICY "Users can only insert their own data" ON public.crm_broadcasts AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_broadcasts; CREATE POLICY "Users can only update their own data" ON public.crm_broadcasts AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_contacts; CREATE POLICY "Users can only access their own data" ON public.crm_contacts AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_contacts; CREATE POLICY "Users can only delete their own data" ON public.crm_contacts AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_contacts; CREATE POLICY "Users can only insert their own data" ON public.crm_contacts AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_contacts; CREATE POLICY "Users can only update their own data" ON public.crm_contacts AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_flow_executions; CREATE POLICY "Users can only access their own data" ON public.crm_flow_executions AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_flow_executions; CREATE POLICY "Users can only delete their own data" ON public.crm_flow_executions AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_flow_executions; CREATE POLICY "Users can only insert their own data" ON public.crm_flow_executions AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_flow_executions; CREATE POLICY "Users can only update their own data" ON public.crm_flow_executions AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_flow_steps; CREATE POLICY "Users can only access their own data" ON public.crm_flow_steps AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_flow_steps; CREATE POLICY "Users can only delete their own data" ON public.crm_flow_steps AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_flow_steps; CREATE POLICY "Users can only insert their own data" ON public.crm_flow_steps AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_flow_steps; CREATE POLICY "Users can only update their own data" ON public.crm_flow_steps AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_flows; CREATE POLICY "Users can only access their own data" ON public.crm_flows AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_flows; CREATE POLICY "Users can only delete their own data" ON public.crm_flows AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_flows; CREATE POLICY "Users can only insert their own data" ON public.crm_flows AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_flows; CREATE POLICY "Users can only update their own data" ON public.crm_flows AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can delete their own google accounts" ON public.crm_google_accounts; CREATE POLICY "Users can delete their own google accounts" ON public.crm_google_accounts AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can insert their own google accounts" ON public.crm_google_accounts; CREATE POLICY "Users can insert their own google accounts" ON public.crm_google_accounts AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_google_accounts; CREATE POLICY "Users can only access their own data" ON public.crm_google_accounts AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_google_accounts; CREATE POLICY "Users can only delete their own data" ON public.crm_google_accounts AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_google_accounts; CREATE POLICY "Users can only insert their own data" ON public.crm_google_accounts AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_google_accounts; CREATE POLICY "Users can only update their own data" ON public.crm_google_accounts AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can update their own google accounts" ON public.crm_google_accounts; CREATE POLICY "Users can update their own google accounts" ON public.crm_google_accounts AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can view their own google accounts" ON public.crm_google_accounts; CREATE POLICY "Users can view their own google accounts" ON public.crm_google_accounts AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_google_tokens; CREATE POLICY "Users can only access their own data" ON public.crm_google_tokens AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_google_tokens; CREATE POLICY "Users can only delete their own data" ON public.crm_google_tokens AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_google_tokens; CREATE POLICY "Users can only insert their own data" ON public.crm_google_tokens AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_google_tokens; CREATE POLICY "Users can only update their own data" ON public.crm_google_tokens AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_messages; CREATE POLICY "Users can only access their own data" ON public.crm_messages AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_messages; CREATE POLICY "Users can only delete their own data" ON public.crm_messages AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_messages; CREATE POLICY "Users can only insert their own data" ON public.crm_messages AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_messages; CREATE POLICY "Users can only update their own data" ON public.crm_messages AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_metrics; CREATE POLICY "Users can only access their own data" ON public.crm_metrics AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_metrics; CREATE POLICY "Users can only delete their own data" ON public.crm_metrics AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_metrics; CREATE POLICY "Users can only insert their own data" ON public.crm_metrics AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_metrics; CREATE POLICY "Users can only update their own data" ON public.crm_metrics AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Super admins can manage all profiles" ON public.crm_profiles; CREATE POLICY "Super admins can manage all profiles" ON public.crm_profiles AS PERMISSIVE FOR ALL TO public USING (crm_is_super_admin(auth.uid())) WITH CHECK (crm_is_super_admin(auth.uid()));
DROP POLICY IF EXISTS "Users can update their own profile" ON public.crm_profiles; CREATE POLICY "Users can update their own profile" ON public.crm_profiles AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can view their own profile" ON public.crm_profiles; CREATE POLICY "Users can view their own profile" ON public.crm_profiles AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Service role only access" ON public.crm_sales_orders; CREATE POLICY "Service role only access" ON public.crm_sales_orders AS PERMISSIVE FOR ALL TO public USING (false) WITH CHECK (false);
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_scheduled_messages; CREATE POLICY "Users can only access their own data" ON public.crm_scheduled_messages AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_scheduled_messages; CREATE POLICY "Users can only delete their own data" ON public.crm_scheduled_messages AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_scheduled_messages; CREATE POLICY "Users can only insert their own data" ON public.crm_scheduled_messages AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_scheduled_messages; CREATE POLICY "Users can only update their own data" ON public.crm_scheduled_messages AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_settings; CREATE POLICY "Users can only access their own data" ON public.crm_settings AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_settings; CREATE POLICY "Users can only delete their own data" ON public.crm_settings AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_settings; CREATE POLICY "Users can only insert their own data" ON public.crm_settings AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_settings; CREATE POLICY "Users can only update their own data" ON public.crm_settings AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_statuses; CREATE POLICY "Users can only access their own data" ON public.crm_statuses AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_statuses; CREATE POLICY "Users can only delete their own data" ON public.crm_statuses AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_statuses; CREATE POLICY "Users can only insert their own data" ON public.crm_statuses AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_statuses; CREATE POLICY "Users can only update their own data" ON public.crm_statuses AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_templates; CREATE POLICY "Users can only access their own data" ON public.crm_templates AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_templates; CREATE POLICY "Users can only delete their own data" ON public.crm_templates AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_templates; CREATE POLICY "Users can only insert their own data" ON public.crm_templates AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_templates; CREATE POLICY "Users can only update their own data" ON public.crm_templates AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Service role can insert CRM webhook logs" ON public.crm_webhook_delivery_logs; CREATE POLICY "Service role can insert CRM webhook logs" ON public.crm_webhook_delivery_logs AS PERMISSIVE FOR INSERT TO service_role WITH CHECK (true);
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_webhook_delivery_logs; CREATE POLICY "Users can only access their own data" ON public.crm_webhook_delivery_logs AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_webhook_delivery_logs; CREATE POLICY "Users can only delete their own data" ON public.crm_webhook_delivery_logs AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_webhook_delivery_logs; CREATE POLICY "Users can only insert their own data" ON public.crm_webhook_delivery_logs AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_webhook_delivery_logs; CREATE POLICY "Users can only update their own data" ON public.crm_webhook_delivery_logs AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only access their own data" ON public.crm_webhooks; CREATE POLICY "Users can only access their own data" ON public.crm_webhooks AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = user_id) OR crm_is_super_admin(auth.uid())));
DROP POLICY IF EXISTS "Users can only delete their own data" ON public.crm_webhooks; CREATE POLICY "Users can only delete their own data" ON public.crm_webhooks AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only insert their own data" ON public.crm_webhooks; CREATE POLICY "Users can only insert their own data" ON public.crm_webhooks AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can only update their own data" ON public.crm_webhooks; CREATE POLICY "Users can only update their own data" ON public.crm_webhooks AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Allow public select" ON public.desconto_alunos_settings; CREATE POLICY "Allow public select" ON public.desconto_alunos_settings AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "Service role only access on trial registrations" ON public.free_trial_registrations; CREATE POLICY "Service role only access on trial registrations" ON public.free_trial_registrations AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only access on trial settings" ON public.free_trial_settings; CREATE POLICY "Service role only access on trial settings" ON public.free_trial_settings AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on inteligencia_fotos_admins" ON public.inteligencia_fotos_admins; CREATE POLICY "Service role only on inteligencia_fotos_admins" ON public.inteligencia_fotos_admins AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on generations" ON public.inteligencia_fotos_generations; CREATE POLICY "Service role only on generations" ON public.inteligencia_fotos_generations AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on inteligencia_fotos_settings" ON public.inteligencia_fotos_settings; CREATE POLICY "Service role only on inteligencia_fotos_settings" ON public.inteligencia_fotos_settings AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Anyone can read active templates" ON public.inteligencia_fotos_templates; CREATE POLICY "Anyone can read active templates" ON public.inteligencia_fotos_templates AS PERMISSIVE FOR SELECT TO public USING ((is_active = true));
DROP POLICY IF EXISTS "Service role can manage templates" ON public.inteligencia_fotos_templates; CREATE POLICY "Service role can manage templates" ON public.inteligencia_fotos_templates AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on inteligencia_fotos_users" ON public.inteligencia_fotos_users; CREATE POLICY "Service role only on inteligencia_fotos_users" ON public.inteligencia_fotos_users AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on license_keys" ON public.license_keys; CREATE POLICY "Service role full access on license_keys" ON public.license_keys AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on license_settings" ON public.license_settings; CREATE POLICY "Service role full access on license_settings" ON public.license_settings AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Anyone can insert analytics" ON public.live_analytics; CREATE POLICY "Anyone can insert analytics" ON public.live_analytics AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Anyone can update own analytics" ON public.live_analytics; CREATE POLICY "Anyone can update own analytics" ON public.live_analytics AS PERMISSIVE FOR UPDATE TO public USING (true);
DROP POLICY IF EXISTS "Service role full access on live_analytics" ON public.live_analytics; CREATE POLICY "Service role full access on live_analytics" ON public.live_analytics AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Anyone can read active live" ON public.live_sessions; CREATE POLICY "Anyone can read active live" ON public.live_sessions AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "Service role full access on live_sessions" ON public.live_sessions; CREATE POLICY "Service role full access on live_sessions" ON public.live_sessions AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on live_settings" ON public.live_settings; CREATE POLICY "Service role full access on live_settings" ON public.live_settings AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only access on admins" ON public.metodo_seguidor_admins; CREATE POLICY "Service role only access on admins" ON public.metodo_seguidor_admins AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Banners are viewable by everyone" ON public.metodo_seguidor_banners; CREATE POLICY "Banners are viewable by everyone" ON public.metodo_seguidor_banners AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "Modules are viewable by everyone" ON public.metodo_seguidor_modules; CREATE POLICY "Modules are viewable by everyone" ON public.metodo_seguidor_modules AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "Service role full access" ON public.metodo_seguidor_modules; CREATE POLICY "Service role full access" ON public.metodo_seguidor_modules AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access" ON public.metodo_seguidor_orders; CREATE POLICY "Service role full access" ON public.metodo_seguidor_orders AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role can manage upsells" ON public.metodo_seguidor_upsells; CREATE POLICY "Service role can manage upsells" ON public.metodo_seguidor_upsells AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Upsells are viewable by everyone" ON public.metodo_seguidor_upsells; CREATE POLICY "Upsells are viewable by everyone" ON public.metodo_seguidor_upsells AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "Service role full access" ON public.metodo_seguidor_users; CREATE POLICY "Service role full access" ON public.metodo_seguidor_users AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access" ON public.metodo_seguidor_videos; CREATE POLICY "Service role full access" ON public.metodo_seguidor_videos AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Videos are viewable by everyone" ON public.metodo_seguidor_videos; CREATE POLICY "Videos are viewable by everyone" ON public.metodo_seguidor_videos AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "Service role only on mro_direct_ai_pauses" ON public.mro_direct_ai_pauses; CREATE POLICY "Service role only on mro_direct_ai_pauses" ON public.mro_direct_ai_pauses AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on mro_direct_automations" ON public.mro_direct_automations; CREATE POLICY "Service role only on mro_direct_automations" ON public.mro_direct_automations AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on mro_direct_known_followers" ON public.mro_direct_known_followers; CREATE POLICY "Service role only on mro_direct_known_followers" ON public.mro_direct_known_followers AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on mro_direct_logs" ON public.mro_direct_logs; CREATE POLICY "Service role only on mro_direct_logs" ON public.mro_direct_logs AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on mro_direct_settings" ON public.mro_direct_settings; CREATE POLICY "Service role only on mro_direct_settings" ON public.mro_direct_settings AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Anyone can create euro order" ON public.mro_euro_orders; CREATE POLICY "Anyone can create euro order" ON public.mro_euro_orders AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Service role full access on mro_euro_orders" ON public.mro_euro_orders; CREATE POLICY "Service role full access on mro_euro_orders" ON public.mro_euro_orders AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Users can delete their own images" ON public.mro_images; CREATE POLICY "Users can delete their own images" ON public.mro_images AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can insert their own images" ON public.mro_images; CREATE POLICY "Users can insert their own images" ON public.mro_images AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can view their own images" ON public.mro_images; CREATE POLICY "Users can view their own images" ON public.mro_images AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Service role full access on mro_orders" ON public.mro_orders; CREATE POLICY "Service role full access on mro_orders" ON public.mro_orders AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.mro_profiles; CREATE POLICY "Users can insert their own profile" ON public.mro_profiles AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can update their own profile" ON public.mro_profiles; CREATE POLICY "Users can update their own profile" ON public.mro_profiles AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can view their own profile" ON public.mro_profiles; CREATE POLICY "Users can view their own profile" ON public.mro_profiles AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can delete their own schedules" ON public.mro_schedules; CREATE POLICY "Users can delete their own schedules" ON public.mro_schedules AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can insert their own schedules" ON public.mro_schedules; CREATE POLICY "Users can insert their own schedules" ON public.mro_schedules AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can update their own schedules" ON public.mro_schedules; CREATE POLICY "Users can update their own schedules" ON public.mro_schedules AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can view their own schedules" ON public.mro_schedules; CREATE POLICY "Users can view their own schedules" ON public.mro_schedules AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Admins can update settings" ON public.mro_settings; CREATE POLICY "Admins can update settings" ON public.mro_settings AS PERMISSIVE FOR ALL TO public USING (((auth.jwt() ->> 'email'::text) = 'mro@gmail.com'::text));
DROP POLICY IF EXISTS "Users can delete their own strategies" ON public.mro_strategies; CREATE POLICY "Users can delete their own strategies" ON public.mro_strategies AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can insert their own strategies" ON public.mro_strategies; CREATE POLICY "Users can insert their own strategies" ON public.mro_strategies AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Users can view their own strategies" ON public.mro_strategies; CREATE POLICY "Users can view their own strategies" ON public.mro_strategies AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));
DROP POLICY IF EXISTS "Service role insert only" ON public.paid_users; CREATE POLICY "Service role insert only" ON public.paid_users AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (false);
DROP POLICY IF EXISTS "Users can delete own data" ON public.paid_users; CREATE POLICY "Users can delete own data" ON public.paid_users AS PERMISSIVE FOR DELETE TO authenticated USING ((email = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)));
DROP POLICY IF EXISTS "Users can update own data" ON public.paid_users; CREATE POLICY "Users can update own data" ON public.paid_users AS PERMISSIVE FOR UPDATE TO public USING ((email = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)));
DROP POLICY IF EXISTS "Users can view own data" ON public.paid_users; CREATE POLICY "Users can view own data" ON public.paid_users AS PERMISSIVE FOR SELECT TO public USING ((email = ((current_setting('request.jwt.claims'::text, true))::json ->> 'email'::text)));
DROP POLICY IF EXISTS "Service role full access on payment_orders" ON public.payment_orders; CREATE POLICY "Service role full access on payment_orders" ON public.payment_orders AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role insert payment orders" ON public.payment_orders; CREATE POLICY "Service role insert payment orders" ON public.payment_orders AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role read payment orders" ON public.payment_orders; CREATE POLICY "Service role read payment orders" ON public.payment_orders AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access promo33" ON public.promo33_users; CREATE POLICY "Service role full access promo33" ON public.promo33_users AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Anyone can read active prompts" ON public.prompts_mro_items; CREATE POLICY "Anyone can read active prompts" ON public.prompts_mro_items AS PERMISSIVE FOR SELECT TO public USING ((is_active = true));
DROP POLICY IF EXISTS "Service role full access on prompts_mro_items" ON public.prompts_mro_items; CREATE POLICY "Service role full access on prompts_mro_items" ON public.prompts_mro_items AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Anyone can create prompts order" ON public.prompts_mro_orders; CREATE POLICY "Anyone can create prompts order" ON public.prompts_mro_orders AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Service role full access on prompts_mro_orders" ON public.prompts_mro_orders; CREATE POLICY "Service role full access on prompts_mro_orders" ON public.prompts_mro_orders AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on prompts_mro_payment_orders" ON public.prompts_mro_payment_orders; CREATE POLICY "Service role full access on prompts_mro_payment_orders" ON public.prompts_mro_payment_orders AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on prompts_mro_settings" ON public.prompts_mro_settings; CREATE POLICY "Service role full access on prompts_mro_settings" ON public.prompts_mro_settings AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on prompts_mro_users" ON public.prompts_mro_users; CREATE POLICY "Service role full access on prompts_mro_users" ON public.prompts_mro_users AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on promptsin_orders" ON public.promptsin_orders; CREATE POLICY "Service role full access on promptsin_orders" ON public.promptsin_orders AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on promptsin_settings" ON public.promptsin_settings; CREATE POLICY "Service role full access on promptsin_settings" ON public.promptsin_settings AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on promptsin_users" ON public.promptsin_users; CREATE POLICY "Service role full access on promptsin_users" ON public.promptsin_users AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Anyone can track visits" ON public.renda_extra_analytics; CREATE POLICY "Anyone can track visits" ON public.renda_extra_analytics AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Service role can view analytics" ON public.renda_extra_analytics; CREATE POLICY "Service role can view analytics" ON public.renda_extra_analytics AS PERMISSIVE FOR SELECT TO public USING ((( SELECT auth.role() AS role) = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on renda_extra_aula_analytics" ON public.renda_extra_aula_analytics; CREATE POLICY "Service role full access on renda_extra_aula_analytics" ON public.renda_extra_aula_analytics AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on renda_extra_aula_leads" ON public.renda_extra_aula_leads; CREATE POLICY "Service role full access on renda_extra_aula_leads" ON public.renda_extra_aula_leads AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on renda_extra_aula_settings" ON public.renda_extra_aula_settings; CREATE POLICY "Service role full access on renda_extra_aula_settings" ON public.renda_extra_aula_settings AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role can manage email logs" ON public.renda_extra_email_logs; CREATE POLICY "Service role can manage email logs" ON public.renda_extra_email_logs AS PERMISSIVE FOR ALL TO public USING ((( SELECT auth.role() AS role) = 'service_role'::text));
DROP POLICY IF EXISTS "Anyone can register as lead" ON public.renda_extra_leads; CREATE POLICY "Anyone can register as lead" ON public.renda_extra_leads AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Service role can manage leads" ON public.renda_extra_leads; CREATE POLICY "Service role can manage leads" ON public.renda_extra_leads AS PERMISSIVE FOR ALL TO public USING ((( SELECT auth.role() AS role) = 'service_role'::text));
DROP POLICY IF EXISTS "Anyone can read active materiais" ON public.renda_extra_materiais; CREATE POLICY "Anyone can read active materiais" ON public.renda_extra_materiais AS PERMISSIVE FOR SELECT TO public USING ((is_active = true));
DROP POLICY IF EXISTS "Service role full access on renda_extra_materiais" ON public.renda_extra_materiais; CREATE POLICY "Service role full access on renda_extra_materiais" ON public.renda_extra_materiais AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role can manage settings" ON public.renda_extra_settings; CREATE POLICY "Service role can manage settings" ON public.renda_extra_settings AS PERMISSIVE FOR ALL TO public USING ((( SELECT auth.role() AS role) = 'service_role'::text));
DROP POLICY IF EXISTS "Anyone can insert v2 analytics" ON public.renda_extra_v2_analytics; CREATE POLICY "Anyone can insert v2 analytics" ON public.renda_extra_v2_analytics AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Service role full v2 analytics" ON public.renda_extra_v2_analytics; CREATE POLICY "Service role full v2 analytics" ON public.renda_extra_v2_analytics AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on renda_extra_v2_email_logs" ON public.renda_extra_v2_email_logs; CREATE POLICY "Service role only on renda_extra_v2_email_logs" ON public.renda_extra_v2_email_logs AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on renda_extra_v2_leads" ON public.renda_extra_v2_leads; CREATE POLICY "Service role only on renda_extra_v2_leads" ON public.renda_extra_v2_leads AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on renda_extra_v2_settings" ON public.renda_extra_v2_settings; CREATE POLICY "Service role only on renda_extra_v2_settings" ON public.renda_extra_v2_settings AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Anyone can insert rendaext_analytics" ON public.rendaext_analytics; CREATE POLICY "Anyone can insert rendaext_analytics" ON public.rendaext_analytics AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Anyone can view rendaext_analytics" ON public.rendaext_analytics; CREATE POLICY "Anyone can view rendaext_analytics" ON public.rendaext_analytics AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "Service role only on rendaext_analytics" ON public.rendaext_analytics; CREATE POLICY "Service role only on rendaext_analytics" ON public.rendaext_analytics AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Anyone can insert audio events" ON public.rendaext_audio_events; CREATE POLICY "Anyone can insert audio events" ON public.rendaext_audio_events AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Service role only on rendaext_email_logs" ON public.rendaext_email_logs; CREATE POLICY "Service role only on rendaext_email_logs" ON public.rendaext_email_logs AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on rendaext_leads" ON public.rendaext_leads; CREATE POLICY "Service role only on rendaext_leads" ON public.rendaext_leads AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on rendaext_orders" ON public.rendaext_orders; CREATE POLICY "Service role only on rendaext_orders" ON public.rendaext_orders AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on rendaext_settings" ON public.rendaext_settings; CREATE POLICY "Service role only on rendaext_settings" ON public.rendaext_settings AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Anyone can manage modules" ON public.sales_modules; CREATE POLICY "Anyone can manage modules" ON public.sales_modules AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Public can view active modules" ON public.sales_modules; CREATE POLICY "Public can view active modules" ON public.sales_modules AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "Anyone can manage tutorials" ON public.sales_tutorials; CREATE POLICY "Anyone can manage tutorials" ON public.sales_tutorials AS PERMISSIVE FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Public can view active tutorials" ON public.sales_tutorials; CREATE POLICY "Public can view active tutorials" ON public.sales_tutorials AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "Service role full access" ON public.squarecloud_user_profiles; CREATE POLICY "Service role full access" ON public.squarecloud_user_profiles AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on tickets" ON public.support_tickets; CREATE POLICY "Service role full access on tickets" ON public.support_tickets AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Only admins can manage roles" ON public.user_roles; CREATE POLICY "Only admins can manage roles" ON public.user_roles AS PERMISSIVE FOR ALL TO authenticated USING (has_role(auth.uid(), 'admin'::app_role));
DROP POLICY IF EXISTS "Users can view their own roles" ON public.user_roles; CREATE POLICY "Users can view their own roles" ON public.user_roles AS PERMISSIVE FOR SELECT TO authenticated USING ((user_id = auth.uid()));
DROP POLICY IF EXISTS "Service role full access" ON public.user_sessions; CREATE POLICY "Service role full access" ON public.user_sessions AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on whatsapp_page_options" ON public.whatsapp_page_options; CREATE POLICY "Service role only on whatsapp_page_options" ON public.whatsapp_page_options AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on whatsapp_page_settings" ON public.whatsapp_page_settings; CREATE POLICY "Service role only on whatsapp_page_settings" ON public.whatsapp_page_settings AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on wpp_bot_messages_v2" ON public.wpp_bot_messages_v2; CREATE POLICY "Service role only on wpp_bot_messages_v2" ON public.wpp_bot_messages_v2 AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on wpp_bot_session_v2" ON public.wpp_bot_session_v2; CREATE POLICY "Service role only on wpp_bot_session_v2" ON public.wpp_bot_session_v2 AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role only on wpp_bot_settings_v2" ON public.wpp_bot_settings_v2; CREATE POLICY "Service role only on wpp_bot_settings_v2" ON public.wpp_bot_settings_v2 AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Allow anyone to view connection logs" ON public.wpp_connection_logs; CREATE POLICY "Allow anyone to view connection logs" ON public.wpp_connection_logs AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "Allow system to insert connection logs" ON public.wpp_connection_logs; CREATE POLICY "Allow system to insert connection logs" ON public.wpp_connection_logs AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Service role full access on zapi_contacts" ON public.zapi_contacts; CREATE POLICY "Service role full access on zapi_contacts" ON public.zapi_contacts AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on zapi_flow_executions" ON public.zapi_flow_executions; CREATE POLICY "Service role full access on zapi_flow_executions" ON public.zapi_flow_executions AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on zapi_flow_steps" ON public.zapi_flow_steps; CREATE POLICY "Service role full access on zapi_flow_steps" ON public.zapi_flow_steps AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Allow public delete on zapi_flows" ON public.zapi_flows; CREATE POLICY "Allow public delete on zapi_flows" ON public.zapi_flows AS PERMISSIVE FOR DELETE TO public USING (true);
DROP POLICY IF EXISTS "Allow public insert on zapi_flows" ON public.zapi_flows; CREATE POLICY "Allow public insert on zapi_flows" ON public.zapi_flows AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Allow public update on zapi_flows" ON public.zapi_flows; CREATE POLICY "Allow public update on zapi_flows" ON public.zapi_flows AS PERMISSIVE FOR UPDATE TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Service role full access on zapi_flows" ON public.zapi_flows; CREATE POLICY "Service role full access on zapi_flows" ON public.zapi_flows AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Users can view flows" ON public.zapi_flows; CREATE POLICY "Users can view flows" ON public.zapi_flows AS PERMISSIVE FOR SELECT TO public USING (true);
DROP POLICY IF EXISTS "Service role full access on zapi_messages" ON public.zapi_messages; CREATE POLICY "Service role full access on zapi_messages" ON public.zapi_messages AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on zapi_settings" ON public.zapi_settings; CREATE POLICY "Service role full access on zapi_settings" ON public.zapi_settings AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Anyone can create zapmro order" ON public.zapmro_orders; CREATE POLICY "Anyone can create zapmro order" ON public.zapmro_orders AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
DROP POLICY IF EXISTS "Service role full access on zapmro_orders" ON public.zapmro_orders; CREATE POLICY "Service role full access on zapmro_orders" ON public.zapmro_orders AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));
DROP POLICY IF EXISTS "Service role full access on zapmro_users" ON public.zapmro_users; CREATE POLICY "Service role full access on zapmro_users" ON public.zapmro_users AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'service_role'::text)) WITH CHECK ((auth.role() = 'service_role'::text));

COMMIT;
