// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { getActiveWhatsAppNumberId } from '@/lib/activeNumberContext';

/**
 * As credenciais chegam por variáveis de ambiente (.env / painel de deploy).
 * Quando elas faltam, `createClient` lançava "supabaseUrl is required." durante
 * o import do módulo — antes de qualquer render — o que derrubava o React
 * inteiro e deixava a tela apenas com a cor de fundo (azul escuro).
 *
 * Usamos valores de placeholder para que a aplicação continue renderizando e o
 * problema apareça no console como aviso, não como tela morta.
 */
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!isSupabaseConfigured) {
  console.warn(
    '[supabase] VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY ausentes. ' +
      'A interface abre, mas chamadas ao backend vão falhar até configurar o .env.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-anon-key',
  {
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);

/**
 * Multi-WhatsApp: todo `functions.invoke` passa a carregar o número aberto
 * (`whatsapp_number_id`). Assim o servidor usa as credenciais daquele número
 * — nunca as do último número ativado — e cada caixa de entrada permanece
 * independente. Feito em um único ponto para não depender de cada chamada.
 */
const originalInvoke = supabase.functions.invoke.bind(supabase.functions);
(supabase.functions as any).invoke = (
  functionName: string,
  options: Record<string, any> = {}
) => {
  const numberId = getActiveWhatsAppNumberId();
  const body = options?.body;
  const canInject =
    !!numberId &&
    body !== null &&
    typeof body === 'object' &&
    !(body instanceof FormData) &&
    !(body instanceof Blob) &&
    !(body instanceof ArrayBuffer) &&
    !Array.isArray(body) &&
    (body as any).whatsapp_number_id === undefined;

  if (!canInject) return originalInvoke(functionName, options as any);

  return originalInvoke(functionName, {
    ...options,
    body: { ...(body as Record<string, unknown>), whatsapp_number_id: numberId },
  } as any);
};
